## Homework 4: Evaluation Metrics for Classification

In [9]:
import pandas as pd
import numpy as np

# Load the dataset
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv"
df = pd.read_csv(url)

# Make everything lower case and change spaces to underscores (in both headings and data)
df.columns = df.columns.str.lower().str.replace(' ', '_')
strings = list(df.dtypes[df.dtypes == 'object'].index)
for col in strings:
    df[col] = df[col].str.lower().str.replace(' ', '_')

df

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1
...,...,...,...,...,...,...,...,...,...
1457,referral,manufacturing,1,NaN,self_employed,north_america,4,0.53,1
1458,referral,technology,3,65259.0,student,europe,2,0.24,1
1459,paid_ads,technology,1,45688.0,student,north_america,3,0.02,1
1460,referral,NaN,5,71016.0,self_employed,north_america,0,0.25,1
1461,organic_search,finance,3,92855.0,student,north_america,3,0.41,1

### Data preparation

Check if the missing values are presented in the features.\
If there are missing values:\
    For caterogiral features, replace them with 'NA'\
    For numerical features, replace with with 0.0

Split the data into 3 parts: train/validation/test with 60%/20%/20% distribution. Use train_test_split function for that with random_state=1

### Question 1. ROC AUC feature importance

ROC AUC could also be used to evaluate feature importance of numerical variables.

Let's do that

For each numerical variable, use it as score (aka prediction) and compute the AUC with the y variable as ground truth.\
    Use the training dataset for that\
    If your AUC is < 0.5, invert this variable by putting "-" in front

(e.g. -df_train['balance'])

AUC can go below 0.5 if the variable is negatively correlated with the target variable. You can change the direction of the correlation by negating this variable - then negative correlation becomes positive.

Which numerical variable (among the following 4) has the highest AUC?\
    lead_score\
    number_of_courses_viewed\
    interaction_count\
    annual_income

### Question 2. Training the model

Apply one-hot-encoding using DictVectorizer and train the logistic regression with these parameters:

LogisticRegression(solver='liblinear', C=1.0, max_iter=1000)

What's the AUC of this model on the validation dataset? (round to 3 digits)

### Question 3. Precision and Recall

Now let's compute precision and recall for our model.\
    Evaluate the model on all thresholds from 0.0 to 1.0 with step 0.01\
    For each threshold, compute precision and recall\
    Plot them

At which threshold precision and recall curves intersect?

### Question 4. F1 score

Precision and recall are conflicting - when one grows, the other goes down. That's why they are often combined into the F1 score - a metrics that takes into account both

Let's compute F1 for all thresholds from 0.0 to 1.0 with increment 0.01

At which threshold F1 is maximal?

### Question 5. 5-Fold CV

Use the KFold class from Scikit-Learn to evaluate our model on 5 different folds:

KFold(n_splits=5, shuffle=True, random_state=1)
    Iterate over different folds of df_full_train\
    Split the data into train and validation\
    Train the model on train with these parameters: LogisticRegression(solver='liblinear', C=1.0, max_iter=1000)\
    Use AUC to evaluate the model on validation

How large is standard deviation of the scores across different folds?

### Question 6. Hyperparameter Tuning

Now let's use 5-Fold cross-validation to find the best parameter C\
    Iterate over the following C values: [0.000001, 0.001, 1]\
    Initialize KFold with the same parameters as previously\
    Use these parameters for the model: LogisticRegression(solver='liblinear', C=C, max_iter=1000)\
    Compute the mean score as well as the std (round the mean and std to 3 decimal digits)\

Which C leads to the best mean score?